sudo: required
language: python
services:
- docker
before_install:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- docker network create DD-DeCaF
script:
- docker-compose run --rm api sh -c "py.test --cov=./schema_collector tests/ && codecov --token $CODECOV_TOKEN"
deploy:
  provider: script
  script: ./push_to_hub_travis.sh
  on:
    all_branches: true
