sudo: required
language: python
services:
- docker
before_install:
- docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- docker network create DD-DeCaF
install: docker-compose up -d
script:
- docker-compose exec web /bin/bash -c "py.test --cov=./schema_collector tests/"
after_success:
- docker-compose exec web /bin/bash -c "codecov --token $CODECOV_TOKEN"
deploy:
  provider: script
  script: ./push_to_hub_travis.sh
  on:
    all_branches: true
