apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidocs-production
spec:
  selector:
    matchLabels:
      app: apidocs
      env: production
  replicas: 1
  template:
    metadata:
      labels:
        app: apidocs
        env: production
    spec:
      containers:
      - name: swagger
        image: swaggerapi/swagger-ui
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: "https://api.dd-decaf.eu/openapi.json"
        resources:
          requests:
            cpu: "1m"
            memory: "32Mi"
          limits:
            cpu: "25m"
      - name: schema-collector
        image: gcr.io/dd-decaf-cfbf6/schema-collector:master
        ports:
        - containerPort: 8900
        resources:
          requests:
            cpu: "1m"
            memory: "32Mi"
          limits:
            cpu: "25m"
        env:
        - name: PYTHONASYNCIODEBUG
          value: "1"
        - name: HOST
          value: api.dd-decaf.eu
        - name: TO_COLLECT
          value: http://iloop-to-model-production,http://gene-to-reactions-production,http://iam-production/iam
        command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:8900", "-t", "20", "-k", "aiohttp.worker.GunicornWebWorker", "schema_collector.app:app"]

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apidocs-staging
spec:
  selector:
    matchLabels:
      app: apidocs
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: apidocs
        env: staging
    spec:
      containers:
      - name: swagger
        image: swaggerapi/swagger-ui
        ports:
        - containerPort: 8080
        env:
        - name: API_URL
          value: "https://api-staging.dd-decaf.eu/openapi.json"
        resources:
          requests:
            cpu: "1m"
            memory: "32Mi"
          limits:
            cpu: "25m"
      - name: schema-collector
        image: gcr.io/dd-decaf-cfbf6/schema-collector:master
        ports:
        - containerPort: 8900
        resources:
          requests:
            cpu: "1m"
            memory: "32Mi"
          limits:
            cpu: "25m"
        env:
        - name: PYTHONASYNCIODEBUG
          value: "1"
        - name: HOST
          value: api-staging.dd-decaf.eu
        - name: TO_COLLECT
          value: http://iloop-to-model-staging,http://gene-to-reactions-staging,http://iam-staging/iam,http://warehouse-staging/warehouse,http://warehouse-to-model-staging/warehouse-to-model
        command: ["gunicorn", "-w", "1", "-b", "0.0.0.0:8900", "-t", "20", "-k", "aiohttp.worker.GunicornWebWorker", "schema_collector.app:app"]
